export const DEVICE_ACTIONS = {
    SET_DEVICE: "SET_DEVICE",
    UPDATE_DEVICE: "UPDATE_DEVICE",
    DELETE_DEVICE: "DELETE_DEVICE",
    GET_DEVICES: "GET_DEVICES",
    GET_DEVICE_BY_SERIAL: "GET_DEVICE_BY_SERIAL",
    GET_DEVICE_BY_IMAGE: "GET_DEVICE_BY_IMAGE",
    GET_DEVICE_BY_OPERATION: "GET_DEVICE_BY_OPERATION",
    GET_DEVICE_BY_BUSINESSES: "GET_DEVICE_BY_BUSINESSES",
}

