export const BOOT_CENTER_CHANNELS = {
    GET_DEVICES: "GET_DEVICES",
    UPDATE_DEVICE: "UPDATE_DEVICE",
    DELETE_DEVICE: "DELETE_DEVICE",
    SET_DEVICE: "SET_DEVICE",          
    FIND_DEVICE: "FIND_DEVICE",        
    FIND_DEVICE_BY_SCOTIAID: "FIND_DEVICE_BY_SCOTIAID",    
    FIND_DEVICE_BY_IMAGE: "FIND_DEVICE_BY_IMAGE",
    FIND_DEVICE_BY_BUSINESS: "FIND_DEVICE_BY_BUSINESS",
    FIND_DEVICE_BY_IMAGE_AND_BUSINESS: "FIND_DEVICE_BY_IMAGE_AND_BUSINESS",             
}
