export const BRANDS_CHANNELS = {
    GET_BRAND: "GET_BRANDS",
    SET_BRAND: "SET_BRANDS",
    UPDATE_BRAND: "UPDATE_BRAND",
    DELETE_BRAND: "DELETE_BRAND",
}

export const PRODUCTS_BRAND = {
    GET_PRODUCT: "GET_PRODUCT",
    UPDATE_PRODUCT: "UPDATE_PRODUCT",
    SET_PROPDUCT: "SET_PRODUCT",
    DELETE_PRODUCT: "DELETE_PRODUCT",
} 
