import {DEVICE_PROPTYPES} from "./DEVICE_PROPTYPES"
import {INPUT_LOGIN_FORM_PROPTYPES} from "./INPUT_LOGIN_FORM_PROPTYPES"
import {CARD_CONTAINER_PROPTYPES, CARD_HEADER_PROPTYPES} from "./CARD_CONTAINER_PROPTYPES"
import {CARDS_CONTAINER_PROPTYPES, CARDS_HEADER_PROPTYPES} from "./CARDS_CONTAINER_PROPTYPES"

export {
    DEVICE_PROPTYPES,
    INPUT_LOGIN_FORM_PROPTYPES,
    CARD_CONTAINER_PROPTYPES,
    CARD_HEADER_PROPTYPES,
    CARDS_CONTAINER_PROPTYPES,
    CARDS_HEADER_PROPTYPES,
}