export const state = [
        {
            builder: "fabricante",
            device: "Equipo",
            model: "Modelo",
            operation: "It Delivery",
            serial: "Serial",
            entryDate: "11/1/2022",
            pxeDate: "",
            operationAssigned: "Sin Imagen",
            scotia: "GSG",
        },
        {
            builder: "fabricante1",
            device: "Equipo1",
            model: "Modelo1",
            operation: "It Support",
            serial: "Serial1",
            entryDate: "12/1/2022",
            pxeDate: "11/7/2022",
            operationAssigned: "ScotiaTech",
            scotia: "GBS",
        },
        {
            builder: "fabricante2",
            device: "Equipo2",
            model: "Modelo2",
            operation: "It Delivery",
            serial: "Serial2",
            entryDate: "12/1/2022",
            pxeDate: "",
            operationAssigned: "Sin Imagen",
            scotia: "GSG",
        },
        {
            builder: "fabricante3",
            device: "Equipo3",
            model: "Modelo3",
            operation: "It Support",
            serial: "Serial3",
            entryDate: "12/1/2022",
            pxeDate: "12/7/2022",
            operationAssigned: "ScotiaTech",
            scotia: "GBS",
        },
        {
            builder: "fabricante4",
            device: "Equipo4",
            model: "Modelo4",
            operation: "It Support",
            serial: "Serial4",
            entryDate: "12/1/2022",
            pxeDate: "",
            operationAssigned: "Sin Imagen",
            scotia: "GSG",
        },
        {
            builder: "fabricante5",
            device: "Equipo5",
            model: "Modelo5",
            operation: "It Delivery",
            serial: "Serial5",
            entryDate: "12/1/2022",
            pxeDate: "12/7/2022",
            operationAssigned: "ScotiaTech",
            scotia: "GBS",
        },
        {
            builder: "fabricante6",
            device: "Equipo6",
            model: "Modelo6",
            operation: "It Delivery",
            serial: "Serial6",
            entryDate: "12/1/2022",
            pxeDate: "12/7/2022",
            operationAssigned: "Finance",
            scotia: "GBS",
        },
        {
            builder: "fabricante7",
            device: "Equipo7",
            model: "Modelo7",
            operation: "It Delivery",
            serial: "Serial7",
            entryDate: "12/1/2022",
            pxeDate: "12/7/2022",
            operationAssigned: "Finance",
            scotia: "GBS",
        },
        {
            builder: "fabricante8",
            device: "Equipo8",
            model: "Modelo8",
            operation: "It Support",
            serial: "Serial8",
            entryDate: "12/1/2022",
            pxeDate: "12/7/2022",
            operationAssigned: "ScotiaTech",
            scotia: "GBS",
        },
        {
            builder: "fabricante9",
            device: "Equipo9",
            model: "Modelo9",
            operation: "It Support",
            serial: "Serial9",
            entryDate: "12/1/2022",
            pxeDate: "12/7/2022",
            operationAssigned: "ScotiaTech",
            scotia: "GBS",
        },
        {
            builder: "fabricante10",
            device: "Equipo10",
            model: "Modelo10",
            operation: "It Support",
            serial: "Serial10",
            entryDate: "12/1/2022",
            pxeDate: "12/7/2022",
            operationAssigned: "ScotiaTech",
            scotia: "GBS",
        },
        {
            builder: "fabricante11",
            device: "Equipo11",
            model: "Modelo11",
            operation: "It Support",
            serial: "Serial11",
            entryDate: "12/1/2022",
            pxeDate: "12/7/2022",
            operationAssigned: "ScotiaTech",
            scotia: "GBS",
        },
        {
            builder: "fabricante12",
            device: "Equipo12",
            model: "Modelo12",
            operation: "It Support",
            serial: "Serial12",
            entryDate: "12/1/2022",
            pxeDate: "12/7/2022",
            operationAssigned: "ScotiaTech",
            scotia: "GBS",
        },
        {
            builder: "fabricante13",
            device: "Equipo13",
            model: "Modelo13",
            operation: "It Support",
            serial: "Serial13",
            entryDate: "12/1/2022",
            pxeDate: "12/7/2022",
            operationAssigned: "ScotiaTech",
            scotia: "GBS",
        },
        {
            builder: "fabricante14",
            device: "Equipo14",
            model: "Modelo14",
            operation: "It Support",
            serial: "Serial14",
            entryDate: "12/1/2022",
            pxeDate: "12/7/2022",
            operationAssigned: "ScotiaTech",
            scotia: "GBS",
        },
]