export const testData = [
        {
            brand: "fabricante",
            product: "Equipo",
            model: "Modelo",
            internOperation: "IT Delivery",
            serial: "Serial",
            entryDate: "11/1/2022",
            pxeDate: "",
            image: "Sin Imagen",
            business: "GSG",
        },
        {
            brand: "fabricante1",
            product: "Equipo1",
            model: "Modelo1",
            internOperation: "IT Support",
            serial: "Serial1",
            entryDate: "12/1/2022",
            pxeDate: "11/7/2022",
            image: "ScotiaTech",
            business: "GBS",
        },
        {
            brand: "fabricante2",
            product: "Equipo2",
            model: "Modelo2",
            internOperation: "IT Delivery",
            serial: "Serial2",
            entryDate: "12/1/2022",
            pxeDate: "",
            image: "Sin Imagen",
            business: "GSG",
        },
        {
            brand: "fabricante3",
            product: "Equipo3",
            model: "Modelo3",
            internOperation: "IT Support",
            serial: "Serial3",
            entryDate: "12/1/2022",
            pxeDate: "12/7/2022",
            image: "ScotiaTech",
            business: "GBS",
        },
        {
            brand: "fabricante4",
            product: "Equipo4",
            model: "Modelo4",
            internOperation: "IT Support",
            serial: "Serial4",
            entryDate: "12/1/2022",
            pxeDate: "",
            image: "Sin Imagen",
            business: "GSG",
        },
        {
            brand: "fabricante5",
            product: "Equipo5",
            model: "Modelo5",
            internOperation: "IT Delivery",
            serial: "Serial5",
            entryDate: "12/1/2022",
            pxeDate: "12/7/2022",
            image: "ScotiaTech",
            business: "GBS",
        },
        {
            brand: "fabricante6",
            product: "Equipo6",
            model: "Modelo6",
            internOperation: "IT Delivery",
            serial: "Serial6",
            entryDate: "12/1/2022",
            pxeDate: "12/7/2022",
            image: "Finance",
            business: "GBS",
        },
        {
            brand: "fabricante7",
            product: "Equipo7",
            model: "Modelo7",
            internOperation: "IT Delivery",
            serial: "Serial7",
            entryDate: "12/1/2022",
            pxeDate: "12/7/2022",
            image: "Finance",
            business: "GBS",
        },
        {
            brand: "fabricante8",
            product: "Equipo8",
            model: "Modelo8",
            internOperation: "IT Support",
            serial: "Serial8",
            entryDate: "12/1/2022",
            pxeDate: "12/7/2022",
            image: "ScotiaTech",
            business: "GBS",
        },
        {
            brand: "fabricante9",
            product: "Equipo9",
            model: "Modelo9",
            internOperation: "IT Support",
            serial: "Serial9",
            entryDate: "12/1/2022",
            pxeDate: "12/7/2022",
            image: "ScotiaTech",
            business: "GBS",
        },
        {
            brand: "fabricante10",
            product: "Equipo10",
            model: "Modelo10",
            internOperation: "IT Support",
            serial: "Serial10",
            entryDate: "12/1/2022",
            pxeDate: "12/7/2022",
            image: "ScotiaTech",
            business: "GBS",
        },
        {
            brand: "fabricante11",
            product: "Equipo11",
            model: "Modelo11",
            internOperation: "IT Support",
            serial: "Serial11",
            entryDate: "12/1/2022",
            pxeDate: "12/7/2022",
            image: "ScotiaTech",
            business: "GBS",
        },
        {
            brand: "fabricante12",
            product: "Equipo12",
            model: "Modelo12",
            internOperation: "IT Support",
            serial: "Serial12",
            entryDate: "12/1/2022",
            pxeDate: "12/7/2022",
            image: "ScotiaTech",
            business: "GBS",
        },
        {
            brand: "fabricante13",
            product: "Equipo13",
            model: "Modelo13",
            internOperation: "IT Support",
            serial: "Serial13",
            entryDate: "12/1/2022",
            pxeDate: "12/7/2022",
            image: "ScotiaTech",
            business: "GBS",
        },
        {
            brand: "fabricante14",
            product: "Equipo14",
            model: "Modelo14",
            internOperation: "IT Support",
            serial: "Serial14",
            entryDate: "12/1/2022",
            pxeDate: "12/7/2022",
            image: "ScotiaTech",
            business: "GBS",
        },
        {
            brand: "fabricante15",
            product: "Equipo15",
            model: "Modelo15",
            internOperation: "IT Support",
            serial: "Serial15",
            entryDate: "12/1/2022",
            pxeDate: "12/7/2022",
            image: "ScotiaTech",
            business: "GSG",
        },
]